# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRoadshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapi.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address_line1', models.CharField(blank=True, max_length=250, null=True)),
                ('company_address_line2', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('company_email', models.CharField(blank=True, max_length=500, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=250, null=True)),
                ('company_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('start_time', models.CharField(blank=True, max_length=15, null=True)),
                ('end_time', models.CharField(blank=True, max_length=15, null=True)),
                ('sales_team', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('distance_next', models.IntegerField(blank=True, default=0, null=True)),
                ('distance_prev', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userroadshowmeetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roadshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userroadshows', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadshowCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('roadshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadshowcities', to='serverapi.Roadshow')),
            ],
        ),
        migrations.CreateModel(
            name='RoadshowDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadshow_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('roadshow_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadshowdates', to='serverapi.RoadshowCity')),
            ],
        ),
        migrations.CreateModel(
            name='RoadshowDinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dinner_date', models.DateField(blank=True, null=True)),
                ('start_time', models.CharField(max_length=15)),
                ('end_time', models.CharField(max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdinner', to=settings.AUTH_USER_MODEL)),
                ('roadshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadshowdinner', to='serverapi.Roadshow')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadshowExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=150)),
                ('expense_description', models.CharField(blank=True, max_length=150, null=True)),
                ('expense_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('expense_time', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userexpenses', to=settings.AUTH_USER_MODEL)),
                ('roadshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadshowexpenses', to='serverapi.Roadshow')),
            ],
        ),
        migrations.CreateModel(
            name='RoadshowFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=150)),
                ('airline_class', models.CharField(blank=True, max_length=150, null=True)),
                ('from_airport', models.CharField(max_length=500)),
                ('to_airport', models.CharField(max_length=500)),
                ('from_date_time', models.DateTimeField(blank=True, null=True)),
                ('to_date_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.CharField(max_length=15)),
                ('end_time', models.CharField(max_length=15)),
                ('from_date', models.DateField()),
                ('distance_to_next', models.IntegerField(blank=True, default=0, null=True)),
                ('distance_to_prev', models.IntegerField(blank=True, default=0, null=True)),
                ('minutes_to_next', models.IntegerField(blank=True, default=0, null=True)),
                ('minutes_to_prev', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userflights', to=settings.AUTH_USER_MODEL)),
                ('roadshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadshowflights', to='serverapi.Roadshow')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadshowHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=150)),
                ('hotel_address', models.CharField(blank=True, max_length=150, null=True)),
                ('hotel_email', models.CharField(blank=True, max_length=150, null=True)),
                ('hotel_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('start_time', models.CharField(blank=True, max_length=15, null=True)),
                ('end_time', models.CharField(blank=True, max_length=15, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userhotels', to=settings.AUTH_USER_MODEL)),
                ('roadshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadshowhotels', to='serverapi.Roadshow')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadshowMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address', models.CharField(blank=True, max_length=500, null=True)),
                ('company_email', models.CharField(blank=True, max_length=500, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('meeting_address', models.CharField(max_length=500)),
                ('meeting_time', models.TimeField()),
                ('distance_next', models.IntegerField(default=0)),
                ('distance_prev', models.IntegerField(default=0)),
                ('minutes_to_next', models.IntegerField(default=0)),
                ('minutes_to_prev', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermeetings', to=settings.AUTH_USER_MODEL)),
                ('roadshow_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadshowmeetings', to='serverapi.RoadshowDate')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadshowRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_name', models.CharField(max_length=150)),
                ('rental_address', models.CharField(blank=True, max_length=150, null=True)),
                ('rental_email', models.CharField(blank=True, max_length=150, null=True)),
                ('rental_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=15, null=True)),
                ('end_time', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrentals', to=settings.AUTH_USER_MODEL)),
                ('roadshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadshowrentals', to='serverapi.Roadshow')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='roadshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='serverapi.Roadshow'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyroadshow',
            name='roadshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapi.Roadshow'),
        ),
    ]
