# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_mode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='serverapi.MeetingMode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='serverapi.MeetingType'),
            preserve_default=False,
        ),
    ]
