# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapi', '0002_auto_20160830_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_mode_other',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type_other',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
