# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapi', '0004_auto_20160901_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadshowrental',
            name='rental_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
