# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapi', '0005_roadshowrental_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadshowrental',
            name='from_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='roadshowrental',
            name='from_city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='roadshowrental',
            name='from_pincode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='roadshowrental',
            name='to_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='roadshowrental',
            name='to_city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='roadshowrental',
            name='to_pincode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
