# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapi', '0006_auto_20160907_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
