# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serverapi', '0023_auto_20161129_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=45)),
                ('meetingFile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('fileType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingDoc', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('comments', models.TextField(blank=True, null=True)),
                ('comment_date', models.CharField(blank=True, max_length=25, null=True)),
                ('fileType', models.CharField(blank=True, max_length=25, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_status',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='meetingsummary',
            name='meetingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_summary', to='serverapi.Meeting'),
        ),
        migrations.AddField(
            model_name='meetingdocument',
            name='meetingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_documents', to='serverapi.Meeting'),
        ),
    ]
