# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapi', '0024_auto_20161221_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMeetingColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapi.Company')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_meeting_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapi.CompanyMeetingColor')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingcolors', to='serverapi.Meeting')),
            ],
        ),
    ]
