# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapi', '0025_companymeetingcolor_meetingcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadshow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
