# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapi', '0026_roadshow_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDefaultMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_messages', to='serverapi.Company')),
            ],
        ),
    ]
